name: Cleanup static web apps

trigger:
  - main

# Add the following variables into devops:
# - DEVOPS_PAT: your personal access token for DevOps
# - AZURE_SUBSCRIPTION: the subscription in azure under which your swa lives
#
# Note: They should be added as secret, but I couldn't make it work with
# the AzureCLI@2 task, so you can only add them as normal variable
variables:
  NPM_CONFIG_CACHE: $(Pipeline.Workspace)/.npm
  DEVOPS_ORG_URL: "https://dev.azure.com/feedm3"
  DEVOPS_PROJECT: "azure-playground"
  AZURE_STATIC_WEBAPP_NAME: "react-app"

jobs:
- job: cleanup_preview_environments_job
  displayName: Cleanup
  pool:
    vmImage: ubuntu-latest
  steps:
  # https://learn.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#nodejsnpm
  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(NPM_CONFIG_CACHE)
    displayName: "Cache npm"

  - script: |
      npm ci
    displayName: "Install dependencies"

  # https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-static-web-app-v0?view=azure-pipelines
  - task: AzureCLI@2
    inputs:
      azureSubscription: "test-service-connection-name"
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        npm run ci:cleanup-deployments
    displayName: "Cleanup outdated deployments"
