name: Deploy static web app

# pipeline can't be triggered as part of a build validation right now:
# - https://github.com/microsoft/azure-pipelines-tasks/issues/17066
#
# the correct trigger here would be the pr trigger, but this is not supported
# in Azure DevOps yet (10-2022)
# https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/pr?view=azure-pipelines
# pr:
#  autoCancel: true
#  branches:
#    include:
#      - main
#
# so we run this job on every branch and not jut active pull request branches
trigger:
  batch: true
  branches:
    include:
      - '*'

# Add the following variables into devops:
# - DEVOPS_PAT: your personal access token for DevOps
# - AZURE_SUBSCRIPTION: the subscription in azure under which your swa lives
#
# Note: They should be added as secret, but I couldn't make it work with
# the AzureCLI@2 task, so you can only add them as normal variable
variables:
  NPM_CONFIG_CACHE: $(Pipeline.Workspace)/.npm
  DEVOPS_ORG_URL: "https://dev.azure.com/feedm3"
  DEVOPS_PROJECT: "azure-playground"
  AZURE_STATIC_WEBAPP_NAME: "react-app"

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-white-dune-044a9f703-variable-group
  steps:
  # https://learn.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#nodejsnpm
  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(NPM_CONFIG_CACHE)
    displayName: "Cache npm"

  - script: |
      npm ci
    displayName: "Install dependencies"


  - script: |
      npm run build
    displayName: "Build app"

  # as we build the app in the pipeline, we only use this AzureStaticWebApp task for uploading
  # if `skip_app_build` is used, `app_location` becomes the upload folder
  # - https://github.com/Azure/static-web-apps/issues/248#issuecomment-790723641
  # - https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-static-web-app-v0?view=azure-pipelines
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_DUNE_044A9F703)
      app_location: "/dist"
      production_branch: 'main'
      skip_api_build: true
      skip_app_build: true
    displayName: "Deploy app"

  - task: AzureCLI@2
    inputs:
      azureSubscription: "test-service-connection-name"
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        npm run ci:post-comment
    displayName: "Post deployment URL"
